---
dist: trusty
language: node_js
node_js:
  - 10

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - echo $HOME && echo $PATH
  - npm install -g bower

install:
  - yarn install --pure-lockfile
  - bower install --config.interactive=false

script:
  - pwd
  - yarn test
  - ember build --ssl false
